### ISSUE TITLE
Plugin missing after update

### ISSUE THREAD

**Issue by kileytoo** [tlovett1/custom-contact-forms#116]
HI there, WordPress has automatically updated itself three times in the last few weeks and now this plugin is missing from the dashboard list. It doesn't even show as inactive. On the website, the code [ccf_form id=”2671″] appears instead of the form.

Is my custom form lost? How can I fix this?

**Comment by kileytoo** [comment]
Any help is much appreciated.

**Comment by kileytoo** [comment]
*looking for a new plugin*

**Comment by BORKG2006** [comment]
Something happened with one of the numerous, recent WordPress updates that affected this plug-in but no one seems to be reading or responding.  Don't know what's going on.

**Comment by kileytoo** [comment]
Thanks for stepping in. I just found several threads on wordpress.org with the same issue being reported eight months ago, six month ago, etc. This appears to be the main thread:

https://wordpress.org/support/topic/forms-vanished-overnight

According to this other thread, the plugin is no longer actively maintained.

https://wordpress.org/support/topic/a-serious-vulnerability-in-the-custom-contact-forms-plugin-has-been-announced

**Comment by tlovett1** [comment]
This is being worked on. Sorry guys. Fix will go out tonight.

**Comment by BORKG2006** [comment]
Jeez, this is getting old.  Had Contact Form 7  up and running and had to kill it due to problems.  Found Custom Contact and it worked (past tense) great until they start doing all the WordPress updates.  

 

FYI, I’ve launched a missile at the developer, Taylor Lovett.  We’ll see what happens.   

 

If they’re not maintaining it why, when I go here: https://wordpress.org/plugins/custom-contact-forms/developers/, does it show:

Requires 3.9 or higher

Compatible up to 4.2.1

Last updated: 2015-4-25

 

If they’re doing updates they must be “maintaining” it is some way shape or form.  I really don’t want to have to reinvent the wheel again but may be forced to if they don’t get their act together fast.  

 

The problem is forms “appear” to not load onto the page but they actually do.  I get the “Camera & Music” icons with the “crawling worm” across the box BUT when I UPDATE the page and then view it the form is there >>>BUT<<< when a user hits submit an UNKNOWN ERROR MESSAGE “sometimes” comes up.  

 

Just tried it again and it worked fine.  I really don’t know WTF is going on with it.  Very irratic. 

 

George B

**Comment by kileytoo** [comment]
Great! I couldn't believe that a well designed plugin with so many installs was not actively maintained...

Now I wonder if it will be enough to update the plugin to get back the form I designed...?

**Comment by BORKG2006** [comment]
Actually, I think they are maintaining it as evidenced by the latest update dtd 4/25.  Additionally, they’ve done a ton of updates.  Consider they’re @ 6.7.1 now and started with 1.0.0 and have followed with 98 updates so they’re not exactly sitting on their laurels.  This is a great, easy to use form that is quite versatile.  With the recent security issues with WordPress they’ve had to scramble to plug the leaks and there’s no way they can notify all 5,000+ plug-in developers nor can they ring all those plug-ins out to check for compatability.  

 

All in all, if  Taylor does what he’s promised, all will be well in Gotham City.

**Comment by tlovett1** [comment]
Guys, this should be fixed in 6.7.2. Thanks for the report! PS. dont disable automatic updates :)

**Comment by kileytoo** [comment]
Thanks for the update and for the advice. Since the plugin doesn't appear in the dashboard, I guess I should go through the manual install process again and overwrite the existing plugin files. Will my custom form be preserved, or do I need to save specific files and restore them after that?

I am asking because none of the threads I found so far for this issue offered a solution (apart from switching to a different plugin).

**Comment by tlovett1** [comment]
Yes, you can override plugin files. This won't remove your forms.

**Comment by BORKG2006** [comment]
I just installed the update and everything is cool now.  Not sure what you mean by “custom” forms though.  I’ve not advanced that far.  I use their templates and they work well for my needs.

**Comment by kileytoo** [comment]
Thank you all, I uploaded the zip file and my form was back online.

I call it a custom form because I created it from scratch (I don't remember even seeing the templates!)
