### ISSUE TITLE
Form won't load

### ISSUE THREAD

**Issue by dgdesigns** [tlovett1/custom-contact-forms#119]
Using Wordpress 4.2.1. Created a beautiful form but it won't load onto page. The image and music icons come up with a black bar moving underneath. When I preview the page it shows the form. However, when I go to the website outside of admin it says Nothing Found.

**Comment by BORKG2006** [comment]
Same issue.  This started about a week ago.  Using 4.2.1.  Happens on both a newly created form and an older, existing form.  The form actually does load when you go to the page preview >>>BUT<<< when used, an error message appears even though the submission went through.  Net result is I'm getting 3 to 6 submissions every time a user hits SUBMIT because they think they're submission did NOT go through.  What gives???

**Comment by tlovett1** [comment]
Should be fixed in 6.7.2
