### ISSUE TITLE
How to make columns in the form?

### ISSUE THREAD

**Issue by andrew2626** [tlovett1/custom-contact-forms#180]
Hello, I am looking to see if it is possible to have colomns in the form. For instance looking to have two or 3 text boxes right next to each other going horizontal rather than vertical. Please let me know if anyone can help. Thank you in advance.

**Comment by tlovett1** [comment]
It would be very tricky but technically possible.

**Comment by andrew2626** [comment]
Any idea on where to start coding the task that I would like to accomplish? Or any codes already written? Any help would be appreciated

**Comment by ceylamoon** [comment]
Not sure if this solves your problem, but I recently wanted to make radio buttons horizontal instead of vertical. There may be an easier/better way to do this, but this is what I came up with:

On the page that contains the form, I ended up wrapping the entire form in some additional HTML:
`<div class="feedback-form">[ccf_form id="<your form id here>"]</div>`

And I added this custom CSS with the help of a custom CSS plugin:
`@media screen and (min-width: 1200px) {
    .feedback-form .choice {
    	display: inline;
        padding: 10px;
    }
}`

I'm checking for the min-width because I want the radio buttons to still show up vertically in small windows - e.g. on cell phones.
